### ISSUE TITLE
Broken link on Next Step on lesson "Product Page"

### ISSUE THREAD

**Issue by luiscvz** [vtex/vtex-courses#100]
**Describe the content problem**  
Broken link on Next Step
  
A clear and concise description of what the problem is.
Make click on "Next Step" at the final of the lesson, don't do any action: only reload the same page

**How do you think it should be?**  
  
Describe how you think it could be better

**Screenshots**   
  

**Additional context**

**Comment by juliarocha** [comment]
I could not replay the error here... do you mind providing me some screen recording showing it?

**Comment by juliarocha** [comment]
Fixed!
