### ISSUE TITLE
Error in Quick View-VTEX

### ISSUE THREAD

**Issue by FelCer** [vtex/vtex-courses#101]
Al realizar el test de este contenido https://developers.vtex.com/learning/docs/course-layout-blocks-step07quick-view-lang-en esta generando un error, mostrando el siguiente mensaje.

``
16:31:31.373 - warn: Block 'product-summary.shelf' was  defined twice, this could cause unexpected behavior. Please check your json files and remove duplicated block definitions. vtex.builder-hub@0.271.3
16:31:31.394 - error: App build failed with message: Error resolving block "product-summary.shelf":
I couldn't find a block "product-selling-price". You need to declare the block or have your app depended on another app that declares it. This error may be caused by a change in behavior resolving blocks from indirect app dependencies. Further info here: https://vtex.io/docs/releases/2019-12-12/declaring-blocks-stemming-from-indirect-dependencies..
16:31:31.397 - error: Error resolving block "product-summary.shelf":
I couldn't find a block "product-selling-price". You need to declare the block or have your app depended on another app that declares it. This error may be caused by a change in behavior resolving blocks from indirect app dependencies. Further info here: https://vtex.io/docs/releases/2019-12-12/declaring-blocks-stemming-from-indirect-dependencies.. vtex.builder-hub@0.271.3
``

### Realice lo siguiente y no funciono:
  
Cambiar:
``
'list-context.product-list': {
   'blocks': [
     'product-summary.shelf'
   ],
   'children': [
     'slider-layout'
   ]
}`` POR
``
'list-context.product-list': {
   'children': [
     'slider-layout'
   ]
}``

y agregar a:
``
"store.home": {
    "blocks": [
     "product-summary.shelf"
    ]
} ``

**Comment by juliarocha** [comment]
Hola, ¿podría mostrarme cómo es su código para su archivo `home.jsonc`? Creo que son algunas declaraciones faltantes...

**Comment by FelCer** [comment]
> Hola, ¿podría mostrarme cómo es su código para su archivo `home.jsonc`? Creo que son algunas declaraciones faltantes...

Si claro mira

```
{
"store.home": { 
    "blocks": [
      "stack-layout#cta",
      "list-context.product-list"
    ]
  },
  "list-context.product-list": {
    "blocks": [
      "product-summary.shelf"
    ],
    "children": [
      "slider-layout"
    ]
  },
  "product-summary.shelf": {
    "children": [
      "modal-trigger#quickview",
      "product-summary-name",
      "product-selling-price"
    ]
  },
  "modal-trigger#quickview": {
    "children": [
      "product-summary-image", 
      "modal-layout#quickview"
    ]
  },
  "modal-layout#quickview": {
    "children": [
      "product-summary-name",
      "product-images",
      "product-summary-sku-selector",
      "product-summary-quantity",
      "add-to-cart-button"
    ]
  }
  "stack-layout#cta": {
    "children": [
      "image#cta", 
      "link#cta"
    ]
  },
  "image#cta": {
    "props": {
      "blockClass": "cta",
      "width": "100%",
      "height": 400,
      "src": "https://appliancetheme.vtexassets.com/assets/app/src/appliancecat___1b7592b49667c6a89203a0997e06bc87.jpg"
    }
  },
  "link#cta": {
    "props": {
      "displayMode": "button",
      "buttonProps": {
        "variant": "primary",
        "size": "large"
      },
      "href": "/washer",
      "label": "Check these awesome discounts"
    }
  }
}
``

**Comment by juliarocha** [comment]
Ok, ese archivo parece estar bien ... ¿Puedes comprobar si esta aplicación `"vtex.product-price": "1.x"` está en el archivo `manifest.json` como dependencia?

**Comment by ViktorPls** [comment]
Tuve el mismo problema 
```
error: App build failed with message: Error resolving block "product-summary.shelf":
I couldn't find a block "product-selling-price". You need to declare the block or have your app depended on another app that declares it. This error may be caused by a change in behavior resolving blocks from indirect app dependencies. Further info here: https://vtex.io/docs/releases/2019-12-12/declaring-blocks-stemming-from-indirect-dependencies..
warn: Block 'product-summary.shelf' was  defined twice, this could cause unexpected behavior. Please check your json files and remove duplicated block definitions. vtex.builder-hub@0.285.4
```

La solucion estuvo en agregar la dependencia `"vtex.product-price": "1.x"` al archivo `manifest.json`.

No deberia estar especificado en la documentacion del lab correspondiente? O por lo menos un enlace a la documentacion de "Quick view".

Saludos!
