### ISSUE TITLE
erro ao linkar o app

### ISSUE THREAD

**Issue by pratesrodrigo** [vtex/vtex-courses#102]
Segui o tutorial do curso https://developers.vtex.com/learning/lang-pt/docs/course-service-course-step03events-lang-pt até o ponto step03events porém, ao linkar o app no final ele informa no console a seguinte mensagem: Event handler not found for liveUserUpdate service-node@6.28.2

Cheguei a utilizar os mesmos arquivos disponíveis no Gabarito, porém continua dando a mesma mensagem.

Conseguem me ajudar a resolver o problema ?

**Comment by juliarocha** [comment]
Oi Rodrigo! Claro! seu código ta em algum rep para eu dar uma olhada?
