### ISSUE TITLE
[Flex-Layout] Block name highlight with mismatch character

### ISSUE THREAD

**Issue by igorbrasileiro** [vtex/vtex-courses#103]
**Describe the content problem**  
In the [flex-layout](https://developers.vtex.com/learning/docs/course-layout-blocks-step02flexlayout-lang-en) course, the `image# major-appliance` isn't highlighted.

**How do you think it should be?**  
`image# major-appliance` should be highlighted

**Screenshots**   
![image](https://user-images.githubusercontent.com/15680320/104047848-1521b280-51c1-11eb-9b46-6ddd36055abe.png)

**Additional context**  
None

**Comment by juliarocha** [comment]
Thank you for pointing that out! Fixing it now! 🔧
