### ISSUE TITLE
 I am not able to create a workspace

### ISSUE THREAD

**Issue by devDanielCespedes** [vtex/vtex-courses#107]
Hello, how are you? 
I am starting to study a VTEX and am not able to create my workspace.
 I've tried to put several names, however, always the same error: Failed to create workspace 'danielcespedesworkspace': Request failed with status code 403 ErrorID: 1a92e4d10029c191fa2ef55a6623d701  
 I have already tried to access the account on the site, but because I did not create the workspace, I am not authorized to access it. Can you help me please?

**Comment by FabianaFerreira** [comment]
Hi, @devDanielCespedes! How are you? Which account are you using? Can you send me the email that you used to log in to the account, so I can check if the user is valid? Thank you!
It seems to me that the fact of you not being able to access the account on the browser is not related to creating a workspace. It might be a problem of not having a user for that account

**Comment by zagamendes** [comment]
I have the same problem izaacmendes2@gmail.com I'm using this account appliancetheme
