### ISSUE TITLE
Erro login

### ISSUE THREAD

**Issue by Felipelourenco-dev** [vtex/vtex-courses#115]
Hello, when I am directed to the login screen when logging give an error saying ..

You do not have permission
The email felipelourenco.m05@gmail.com does not have permission to access the admin. Contact the person in charge at your company.

**Comment by FabianaFerreira** [comment]
Hi, @Felipelourenco-dev! Are you trying to log in to which account?

**Comment by Felipelourenco-dev** [comment]
I type vtex login appliancetheme and go to the login screen .. do i have to have a special account?

**Comment by FabianaFerreira** [comment]
You need to have a valid user on that account so you can log in. In case you already have a VTEX account, you can use it instead of `appliancetheme`. If that is not the case, you can send me your e-mail, so I can create a user for you on `appliancetheme`.

**Comment by AlejandraMoralesB** [comment]
Hi, THE SAME HAPPENS TO ME, I CANNOT START SECTION
![image](https://user-images.githubusercontent.com/51416478/108636392-ba3bd600-7463-11eb-9364-2e6fdc7169de.png)

**Comment by Felipelourenco-dev** [comment]
FabianaFerreira I am grateful ..  email: felipelourenco.m05@gmail.com

**Comment by FabianaFerreira** [comment]
Hi, @Felipelourenco-dev! I've just created a user for you. You probably received an email.

**Comment by FabianaFerreira** [comment]
Hi, @AlejandraMoralesB! I've just created a user for you on the `appliancetheme` account. You probably received an email. 
In case of not being able to log in or create a workspace, can you try logging out and logging in right after? Thank you!

**Comment by Felipelourenco-dev** [comment]
Hello, I was able to create the account and workspace, but now when entering the following error.. 

Account not found. Please ensure this account is active on the VTEX platform.

workspace: lourencofelipe
I'm trying to enter via the link  lourencofelipe-appliancetheme.myvtex.com

**Comment by Felipelourenco-dev** [comment]
@FabianaFerreira  agora que fui ver que você é brasileira kkk .. então consegui criar o workspace, mas quando tento entrar da Conta não encontrada. Certifique-se de que esta conta esteja ativa na plataforma VTEX.

**Comment by FabianaFerreira** [comment]
Oi, @Felipelourenco-dev! Sim, sou sim. A loja está ativa, é bem estranho você estar enfrentando esse erro, eu acabei de criar um usuário para você nesta conta, provavelmente você recebeu um email há pouco.

Tente acessar [](appliancetheme.myvtex.com) daqui a uns minutos para ver se consegue logar. Depois disso, faça um `vtex logout` e depois `vtex login appliancetheme`.

**Comment by Felipelourenco-dev** [comment]
PS C:\Users\Cliente> vtex whoami
20:04:25.664 - info: Logged into appliancetheme as felipelourenco.m05@gmail.com at production workspace master
PS C:\Users\Cliente> vtex use felipelourencodev
20:06:24.857 - info: Workspace change: You are now using the workspace felipelourencodev on account appliancetheme.

Depois de eu fazer isso... tento entrar em https://felipelourencodev-appliancetheme.myvtex.com/  não funciona

**Comment by Frankjvzla05** [comment]
Olá eu fiz os passos para me cadastrar no vtex.io e ele não me dá acesso.

![image](https://user-images.githubusercontent.com/79920874/109661435-bf2a1500-7b48-11eb-8f52-5ad04a44520b.png)

**Comment by Felipelourenco-dev** [comment]
@FabianaFerreira  consegui finalmente, agora estou com um outro problema! eu usei o vtex link para linkar a pasta a conta só que faço alterações não muda nada

**Comment by FabianaFerreira** [comment]
@Felipelourenco-dev está no workspace correto? se quiser, me mande o link do repositório e do workspace.

**Comment by FabianaFerreira** [comment]
@Frankjvzla05 você pode me informar seu email para eu verificar se você tem acesso a conta? obrigada!

**Comment by Frankjvzla05** [comment]
Hola mi correo de la empresa es: fmaduro@ecomsur.com

**Comment by nmartinez1802** [comment]
Hello, i don't have access to apliancetheme workspace, how i could get it?

**Comment by pvaldebe** [comment]
Hi!! 
I cant logged in muy account vtex io, I need help please.
mail: pvaldebenito@ecomsur.com

![image](https://user-images.githubusercontent.com/80286721/110376907-856a7a00-8032-11eb-9b65-dd59506795b8.png)

**Comment by FabianaFerreira** [comment]
hi, @nmartinez1802. can you send me your email, please?

**Comment by FabianaFerreira** [comment]
hi, @pvaldebe! I've just created a user for you in `appliancetheme` account. Can you try to log in and see if works? Thank you!

**Comment by FabianaFerreira** [comment]
hola, @Frankjvzla05! yo he creado un usuario para usted en la cuenta `appliancetheme`

**Comment by Frankjvzla05** [comment]
Muito obrigado !

**Comment by nmartinez1802** [comment]
> hi, @nmartinez1802. can you send me your email, please?

Hi, nmartinez@ecomsur.com

**Comment by nmartinez1802** [comment]
Hi! @FabianaFerreira my email is nmartinez@ecomsur.com

**Comment by pvaldebe** [comment]
I can,
 have a nice afternoon.
very thanks!

**Comment by tdgm** [comment]
@fabianaferreira boa tarde! Estou com o mesmo problema que o @Felipelourenco-dev estava, consigo fazer o login com minha conta do gmail mas não consigo criar um workspace para seguir com o curso. email: thiago.giudice@gmail.com 
Poderia me ajudar? grande abraço
