### ISSUE TITLE
Admin app build failed: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by mbolka** [vtex/vtex-courses#116]
I have created an admin service following this documentation: https://learn.vtex.com/docs/course-admin-step02-navigation-routes-lang-en.
I have requested a permission to create an app via form and received an approval.
Upon running `vtex link` I receive error:
```
13:25:45.084 - error: Error while retrieving list of versions for app [ACCOUNT NAME].[APP NAME]. vtex.builder-hub@0.272.3  
13:25:45.085 - error: Request failed with status code 500 vtex.builder-hub@0.272.3  
13:25:45.088 - error: App build failed with message: invalid character '<' looking for beginning of value
```
No additional code was added comparing to the code from the training.

**Comment by FabianaFerreira** [comment]
Hi, @mbolka! Can you send me your project so I can have a look, maybe push it to GitHub? You can also send me a snippet of your `manifest.json` file.

**Comment by mbolka** [comment]
I have sent you an invitation to my repository and here is the manifest.json
`{
  "vendor": "[ACCOUNT NAME]",
  "name": "[APP NAME]",
  "version": "0.0.0",
  "title": "Admin Tool",
  "description": "Some admin tool",
  "builders": {
    "react": "3.x",
    "messages": "1.x",
    "docs": "0.x",
    "admin": "0.x"
  },
  "dependencies": {
    "vtex.styleguide": "9.x"
  },
  "registries": ["smartcheckout"],
  "policies": [],
  "$schema": "https://raw.githubusercontent.com/vtex/node-vtex-api/master/gen/manifest.schema"
}
`

**Comment by FabianaFerreira** [comment]
So, the problem lies in both fields: `vendor` and `name`, which should be something different from what you have. Whenever you link your application, it will validate the information that you have in the manifest.json file. That's why it's complaining.

If you send a request to create an app and received approval, you probably defined a vendor name (which should be the same as the account name that you're currently developing in), and the app name. I took a look at the requests and it seems that you used a value for the vendor (`divantetest`) that is not a valid account name. Which is the current account that you're developing?

**Comment by mbolka** [comment]
I am developing the app for: divantetest--vtexromania.myvtex.com
I have requested permission for:
Vendor: divantetest
App: divante-admin-sandbox

**Comment by FabianaFerreira** [comment]
So, you need to do some things to make it work:

1. Change the vendor and the app name on the manifest.json file to the correct ones, which should be:
```json
{
  "vendor": "vtexromania",
  "name": "divante-admin-sandbox",
  "version": "0.0.0",
  "title": "Admin Tool",
  "description": "Some admin tool",
  "builders": {
    "react": "3.x",
    "messages": "1.x",
    "docs": "0.x",
    "admin": "0.x"
  },
  "dependencies": {
    "vtex.styleguide": "9.x"
  },
  "registries": ["smartcheckout"],
  "policies": [],
  "$schema": "https://raw.githubusercontent.com/vtex/node-vtex-api/master/gen/manifest.schema"
}
```

2. You'll probably have to send a new request to be able to link under this account. This request needs to be made with the vendor and app name that I've mentioned before, in the code snippet.

> The vendor is the field that defines which is the account responsible for maintaining the application. It needs to be a valid VTEX account, in your case, `vtexromania`.

**Comment by FabianaFerreira** [comment]
I've just approved the new submission for developing an app under the correct vendor.
