### ISSUE TITLE
Master Data dependencies

### ISSUE THREAD

**Issue by btarbell** [vtex/vtex-courses#119]
**What exactly you didn't understand?**  
  
I believe this step assumes that a specific store template is set up, called appliance-store. Running through the entire course, there was no place that indicated where to find and install this. I am assuming that the data entity "course_backend_product_list" is defined somewhere. 

I'm getting an error after link and event fire that includes the message: "data: { Message: "Field 'slug' not found in schema" }"

**What have you tried so far?**  
  
A clear and concise description of what you tried to do already.

**Additional info**  
  
Add extra content here (code samples, screenshots,...)

**Comment by juliarocha** [comment]
Hi Bill! 
Yeah, we were assuming that everybody taking this course was using one of your sandbox accounts that are already configured in Master Data. I just opened a PR to add this pre-setup for any account, you can check it out here in [this link](https://github.com/vtex/vtex-courses/pull/120). And please, I'm open to every feedback! Feel free to tell us if something isn't clear. And let me know if this is enough for unblocking you!
