### ISSUE TITLE
Página de produto não abre

### ISSUE THREAD

**Issue by trewous** [vtex/vtex-courses#122]
**What exactly you didn't understand?**  
  Depois de criar a página de produto, a mesma não carrega, abre a página definida no CMS

**Additional info**  

Ao tentar buscar o produto na search bar, a barra azul fica carregando e para no final, não carregando a página de produto.
Na verdade, o mesmo erro ocorre para a página Search, abre a configurada no CMS.

**Comment by trewous** [comment]
Descobri o problema, meus workspaces vem com o app vtex.colossus-legacy-proxy. Desinstalei esse app e instalei o vtex.rewriter, o problema foi corrigido.
Sugiro colocar isso em algum lugar ou documentaçao do IO =)

**Comment by juliarocha** [comment]
Que bom que conseguiu resolver!! Obrigada pela sugestão! 😄

**Comment by eficaz-rafaelak** [comment]
@trewous Estou com o mesmo problema, mas não consegui desinstalar o vtex.colossus-legacy-proxy. Aparece uma mensagem falando que não é permitido desinstalar pois ele faz parte da account edition. Poderia me informar, por favor, como você fez para desinstalar?

**Comment by trewous** [comment]
Olá @eficaz-rafaelak , talvez não seja necessário desinstalar ele, somente instalar o rewriter, não testei. Além disso sua conta já é Store Edition? Pode ser isso também.

**Comment by eficaz-rafaelak** [comment]
@trewous Obrigada por responder. Instalei o rewriter, mas não deu certo. Minha conta é Store Edition.
