### ISSUE TITLE
Workflow publishing react app

### ISSUE THREAD

**Issue by arielapaula** [vtex/vtex-courses#125]
**What exactly you didn't understand?**  
I finished the course of Custom Block and succesfully linked the CountDown app with my store. So far I only have the CountDown app linked, i didn't publish it. What steps should I take for publishing the app (not the store) and using the countdown app in production?
 
**Additional info**  
 My store is already in production, I don't need help publishing the store, just the CountDown app.

**Comment by gris** [comment]
Hello @arielapaula. Maybe this article can help you https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-making-your-new-app-version-publicly-available
