### ISSUE TITLE
How can i acces to the vtex.catalog-graphql in a graphql query

### ISSUE THREAD

**Issue by arielapaula** [vtex/vtex-courses#129]
**What exactly you didn't understand?**  
  
I am trying to replicate a query that i generated in the GraphQl IDE (see screenshot above) but i don't understand how to import the vtex.catalog-graphql in the react app.

**What have you tried so far?**  
  
I tried using the same query in the component(see 2nd screenshot) but I get undefined in both console.log

**Additional info**  
  
![image](https://user-images.githubusercontent.com/36748003/112700724-84787b80-8e6d-11eb-8045-374e0e0edee4.png)
![image](https://user-images.githubusercontent.com/36748003/112702362-fd79d200-8e71-11eb-9a2d-759ba1e46d62.png)

**Comment by gris** [comment]
Hi, please direct this question to https://support.vtex.com/hc/en-us/. This repo is only for courses related questions.
