### ISSUE TITLE
How to use StorefrontFunctionComponent

### ISSUE THREAD

**Issue by MateusGuedess** [vtex/vtex-courses#130]
**What exactly you didn't understand?**  

How can I use StorefrontFunctionComponent? 
Where can I add it? 
I'm trying to use but I just getting this error

```
../../.../react/components/AugmentedRealityBanners/index.tsx:19:32 
    TS2304: Cannot find name 'StorefrontFunctionComponent'.
```

**What have you tried so far?**  
I copy all the manifest from tutorial and nothing

**Additional info**  
  
Add extra content here (code samples, screenshots,...)
<img width="902" alt="Captura de Tela 2021-03-29 às 14 50 44" src="https://user-images.githubusercontent.com/22087652/112878510-6c3b7300-909e-11eb-8244-d2fb533384c2.png">

**Comment by gris** [comment]
Hello, Mateus, this repo is only for courses related questions. Please direct your question for the appropriate support channel.
