### ISSUE TITLE
Should use two dashes to access a workspace on browser

### ISSUE THREAD

**Issue by helioricardo** [vtex/vtex-courses#132]
Wrong information on how to access a workspace trought browser.

On page https://learn.vtex.com/docs/course-basic-blocks-step00setup-lang-pt, for two times we got the information on how to access a workspace trhougth browser as https: // ** devworkspace- appliancetheme **. myvtex.com.

Note that it informs to use one dash between the workspace name and the account name. I should use only one dash.

https://nimb.ws/bAM4fN

Thank you

**Comment by carolinamenezes** [comment]
Thanks for your feedback, Helio! We have just fixed it.
