### ISSUE TITLE
No acceso a cuenta appliancetheme

### ISSUE THREAD

**Issue by ivongarduno** [vtex/vtex-courses#134]
**Describe the content problem**  
  
No me permite hacer login, la primera vez que hice **vtex login appliancetheme** me firme con mi cuenta de google y sí accedí, al crear un workspace me arrojo error y al ejecutar **vtex whoami** me indico que no estaba logueada, a partir de ahí con cualquier cuenta que trate de firmarme me rechaza el acceso

**How do you think it should be?**  
  
Describe how you think it could be better

**Screenshots**   
  
![image](https://user-images.githubusercontent.com/51391946/114122392-c960d100-98b5-11eb-9933-e8cc8b91e0d6.png)

**Additional context**

**Comment by jon-by** [comment]
same problem here, @ivongarduno did you solved it?

**Comment by ivongarduno** [comment]
No, I still have this problem

**Comment by georgebrindeiro** [comment]
Hi @jon-by and @ivongarduno, we are currently offering access to the `appliancetheme` test store only to developers who do not have access to any VTEX account. You can consider it a generic account name, as we mention in the [Setting up your Environment](https://learn.vtex.com/page/setting-up-your-environment) step.

If you do not have access to a VTEX account, [sign up to become a VTEX partner](https://vtex.com/us-en/partner/).
