### ISSUE TITLE
As mudanças não renderizam

### ISSUE THREAD

**Issue by Felipelourenco-dev** [vtex/vtex-courses#135]
Fiz todos os procedimentos na instalação e configuração

O comando vtex link da como successfully,
Mas quando abro o vtex browse, fica tudo em branco e aparece apenas o header

**Comment by Felipelourenco-dev** [comment]
Faço as mudanças que o curso indica e não muda nada, agora se eu troco algo no header que já veio pronto funciona

**Comment by georgebrindeiro** [comment]
Oi Felipe, tudo bom?

Você consegue me passar mais informações sobre o passo específico que você está tentando completar, incluindo a conta VTEX que está usando e o código que você disse estar funcionando?

**Comment by Felipelourenco-dev** [comment]
Então faço todos os passos que são pedidos, e inicio as aulas e incluo os códigos da aula! 
Vou lá e Salvo e dou um vtex link e nada muda, agora se eu trocar algo em um código já existente as mudanças acontecem


**Código que estou tentando executar**
 {
  "store.home": {
    "blocks": [
      "rich-text",
      "info-card#button-right",
      "info-card#button-left",
      "flex-layout.row"
    ]
  },
 
  "flex-layout.row": {
    "children": ["info-card#rethink", "flex-layout.col"]
  },
  "flex-layout.col": {
    "children": ["image#electronics", "image#major-appliance"]
  },
  "info-card#rethink": {
    "props": {
      "imageUrl": "https://appliancetheme.vteximg.com.br/arquivos/utensilios-cozinha-min.png",
      "isFullModeStyle": true,
      "headline": "Time to rethink your kitchen",
      "callToActionText": "Discover",
      "textPosition": "center"
    }
  },
  "image#electronics": {
    "props": {
      "src": "https://appliancetheme.vteximg.com.br/assets/vtex.file-manager-graphql/images/electronics_banner___25d69b49f8224b369375e68513b4d593.png",
      "maxWidth": "100%"
    }
  },
  "image#major-appliance": {
    "props": {
      "src": "https://appliancetheme.vteximg.com.br/assets/vtex.file-manager-graphql/images/major_appliance_banner___bb10093866a127345ddfbcca3efa5022.png",
      "maxWidth": "100%"
    }
  }
}

**Conta que estou utilizando**
Account: appliancetheme
Workspace: felipelourencovtex
email: felipelourenco.m05@gmail.com

**Comment by georgebrindeiro** [comment]
Qual dos [cursos](https://learn.vtex.com/page/learning-path-lang-pt) você tá fazendo? E qual passo?

**Comment by Felipelourenco-dev** [comment]
Blocos básicos, logo no primeiro passo nada muda! 

{
  "store.home": {
    "blocks": ["rich-text"]
  },
  "rich-text": {
    "props": {
      "text": "**Hello, World!**",
      "textPosition": "RIGHT"
    }
  }
}

**Comment by georgebrindeiro** [comment]
Realmente, não estou conseguindo também. Me parece ser algum problema na configuração da loja de testes `appliancetheme` relacionada especificamente à home page, vou pedir ajuda internamente para investigar mais a fundo.

Por hora, você pode experimentar esse mesmo código na página de resultados de busca _search.json_:

```json
// store/blocks/search.jsonc
{
  "store.search": {
    "blocks": ["rich-text"]
  },
  "rich-text": {
    "props": {
      "text": "**Hello, World!**",
      "textPosition": "RIGHT"
    }
  }
}
```

Substituindo esse código lá e fazendo uma busca qualquer, você deve conseguir ver o bloco que definiu. Acabei de fazer aqui.

**Comment by georgebrindeiro** [comment]
Descobri o problema! Ao linkar o `minimum-boilerplate-theme`, você precisa selecionar o template no CMS:

https://felipelourencovtex--appliancetheme.myvtex.com/admin/cms/pages/store.home/

![image](https://user-images.githubusercontent.com/2094877/116321448-754c5c80-a790-11eb-955f-d324938ca011.png)

Para identificar quais blocos estão sendo carregados na página, você pode executar `__RUNTIME__.extensions` no console do Chrome DevTools. Ele vai mostrar os blocos sendo renderizados e vai ter o blockId, que vai mostrar qual app de tema tá renderizando um bloco específico.

![image (1)](https://user-images.githubusercontent.com/2094877/116321571-aaf14580-a790-11eb-99eb-4df78c51919e.png)
