### ISSUE TITLE
access - course vtex   /vtex-apps/demostore-theme

### ISSUE THREAD

**Issue by pvaldebe** [vtex/vtex-courses#146]
Hi, 
I'm taking the course, I not have the access for https://github.com/vtex-apps/demostore-theme
I need access, pvaldebenito@ecomsur.com

I have a problem, when wanted to do login in this project https://learn.vtex.com/docs/course-store-performance-step01fold-block-lang-en 

I get error!

![img](http://imgfz.com/i/Ca1E4Dc.png)

You help my please, Regards!

**Comment by fabianaferreira** [comment]
Usually, the account that we use for the courses is not `demostore`, but `appliancetheme`.
