### ISSUE TITLE
Erro criação de workplace

### ISSUE THREAD

**Issue by tdgm** [vtex/vtex-courses#147]
@fabianaferreira boa tarde! Estou com o mesmo problema que o @Felipelourenco-dev estava na issue #115, consigo fazer o login com minha conta do gmail mas não consigo criar um workspace para seguir com o curso. email: thiago.giudice@gmail.com
Poderia me ajudar? grande abraço

**Comment by fabianaferreira** [comment]
Olá, @tdgm! Tudo bem? Acabei de te dar acesso a conta `appliancetheme`. Você deve ter recebido um email.

**Comment by fabianaferreira** [comment]
olá, @tdgm! acabei de dar acesso ao email que você enviou agora. veja se está funcionando.

**Comment by tdgm** [comment]
@fabianaferreira obrigado! consegui criar o workspace!

**Comment by juliogomes92** [comment]
@fabianaferreira boa tarde! Tudo bem? Estou também com o mesmo problema que o @Felipelourenco-dev e o @tdgm, consigo fazer o login com minha conta do gmail mas não consigo criar um workspace para seguir com o curso. 
email: julio.gomes92@gmail.com
Agradeço muito!

**Comment by zagamendes** [comment]
oi pode me ajudar também? izaacmendes2@gmail.com
