### ISSUE TITLE
Vtex cli installation don't proceed

### ISSUE THREAD

**Issue by pablolucio97** [vtex/vtex-courses#154]
Vtex CLI installation doesn't proceed at using the command suggested for the docs:  npm i -g vtex
  
Npm don't proceed with the installation, I already tried using yarn but the cmd doesn't recognize commands from "vtex".  
  
<img src="https://i.ibb.co/pXwJfpN/npm-error.png">
  

I already reinstalled the Node and my current Node version is 4.17.4

**Comment by eranda-clouda** [comment]
You may need to include the Yarn location in path.

Check the troubleshooting part in Installing VTEX IO's CLI documentation.

https://vtex.io/docs/recipes/development/vtex-io-cli-install/
