### ISSUE TITLE
Logo da VTEX quebrada

### ISSUE THREAD

**Issue by mariaeduardaxs** [vtex/vtex-courses#155]
**Describe the content problem**  
  
A url da logo da VTEX não renderiza nem no header, nem no footer.

**How do you think it should be?**  
 
Deve-se substituir a url da logo nos arquivos header.jsonc e footer.jsonc.
Uma possibilidade é utilizar essa URL: "https://upload.wikimedia.org/wikipedia/commons/a/a9/VTEX_Logo.svg"

**Screenshots**   
  
<img width="1204" alt="Captura de Tela 2021-08-06 às 02 07 09" src="https://user-images.githubusercontent.com/45014607/128458883-071813d9-52b6-41e8-b8d8-f8fb3b4ae6ee.png">

**Comment by mariaeduardaxs** [comment]
A logo do footer pode ser substituída por:  https://vtexpayment.vtexassets.com/_v/public/assets/v1/published/vtex.store-footer@2.23.0/public/react/349e2c1974cbd00ab8b8f0de7448e207.svg

**Comment by drianoaz** [comment]
A logo da vtex ainda está quebrada. Alguém pode dar uma ajuda com isso?
