### ISSUE TITLE
Lição não endereça carregar produtos

### ISSUE THREAD

**Issue by antonio-teixeira** [vtex/vtex-courses#196]
Estou fazendo o passo a passo de learn.vtex.com e cheguei na lição da página de produtos (https://learn.vtex.com/docs/course-basic-blocks-step04pdp-lang-pt). Essa lição prevê que haja um catálogo de produtos pré-carregado na sua instalação. Porém, seguindo somente os passos das aulas, isso não acontece.

Seria importante incluir um passo anterior, para usar algo como. o Easysetup (https://developers.vtex.com/vtex-developer-docs/docs/installing-b2b-easy-set-up) para que seja possível concluir essa lição da página de produto com sucesso.

**Comment by walterjaworski** [comment]
Opa, caí nesta situação também. Solicitei a instalação do IO em uma instância para que possamos migrar do legado para IO, mas ao chegar nesta etapa, também não consigo carregar produtos da loja ou produtos de demonstração.

**Comment by antonio-teixeira** [comment]
@walterjaworski se você tentar o app de easysetup que coloquei ali, ele popula com produtos na instância. Agora o problema é que o aplicativo não está enxergando os produtos.
