### ISSUE TITLE
 Information divergence between class content and answer sheet - Layout block course, step 8 lesson

### ISSUE THREAD

**Issue by felipealmeidacorrea** [vtex/vtex-courses#217]
**Describe the content problem**  
  
The block class of image#cta's props is filled as "cta" in the answer sheet, unlike what is presented in the step 8 lesson, point 3, line 5 which shows it filled as "cover" (https://learn.vtex.com/docs/course-layout-blocks-step08stack-layout-lang-pt). If it is filled in as "cta" it will not show the background image as shown in the example of the lesson which causes confusion in the students' minds

**How do you think it should be?**  
  
It can be solved by correcting the information in the answer sheet, changing the string "cta" to "cover". Home.jsonic file in path "vtex-courses/courses/layout-blocks/steps/08_stack-layout/answersheet/home.jsonc" line 10, position 24.

**Screenshots**   

The content of lesson now:
<img style="height: 100px" src="https://i.ibb.co/2cH2tg3/Captura-de-tela-2022-07-13-102556.png" alt="Captura-de-tela-2022-07-13-102556" border="0">

The content of answer sheet now:
<img style="height: 100px" src="https://i.ibb.co/5rb3s5V/Captura-de-tela-2022-07-13-102628.png" alt="Captura-de-tela-2022-07-13-102628" border="0">

**Additional context**  
  
No additional context.

**Comment by fabianaferreira** [comment]
Fixed with #218. Thank you for reporting it!
